# Generated by Django 3.2.13 on 2022-07-09 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Entry_id',
            new_name='entry_id',
        ),
        migrations.AlterField(
            model_name='member',
            name='fees_plan',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='memb_app.fees_plan'),
        ),
    ]
