# Generated by Django 3.2.13 on 2022-07-11 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memb_app', '0002_auto_20220709_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='entry_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memb_app.role'),
        ),
    ]
