# Generated by Django 3.2.13 on 2022-07-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memb_app', '0003_auto_20220711_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
